# Generated by Django 3.1.7 on 2021-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_date_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
