# Generated by Django 3.1.7 on 2021-04-02 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroupAchievement',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaygroupPlayer',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('player_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.playerrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='player_role',
        ),
        migrations.RemoveField(
            model_name='playerachievement',
            name='game_achievement',
        ),
        migrations.RenameModel(
            old_name='Game',
            new_name='Playgroup',
        ),
        migrations.DeleteModel(
            name='GameAchievement',
        ),
        migrations.DeleteModel(
            name='GamePlayer',
        ),
        migrations.AddField(
            model_name='playgroupplayer',
            name='playgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.playgroup'),
        ),
        migrations.AddField(
            model_name='playgroupachievement',
            name='playgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.playgroup'),
        ),
        migrations.AddField(
            model_name='playerachievement',
            name='playgroup_achievement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='achievements.playgroupachievement'),
            preserve_default=False,
        ),
    ]
