# Generated by Django 3.1.7 on 2021-04-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20210402_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgroupplayer',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
