# Generated by Django 3.1.7 on 2021-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_playgroupplayer_date_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
